# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arrangeclass.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(591, 513)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(410, 440, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(60, 10, 431, 71))
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(20, 30, 82, 17))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(150, 30, 82, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(300, 30, 82, 17))
        self.radioButton_3.setObjectName("radioButton_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(60, 160, 431, 71))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_6.setGeometry(QtCore.QRect(20, 30, 82, 17))
        self.radioButton_6.setChecked(True)
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_7.setGeometry(QtCore.QRect(120, 30, 82, 17))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_8.setGeometry(QtCore.QRect(240, 30, 82, 17))
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_9.setGeometry(QtCore.QRect(340, 30, 82, 17))
        self.radioButton_9.setObjectName("radioButton_9")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(60, 250, 431, 61))
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_10.setGeometry(QtCore.QRect(10, 30, 82, 17))
        self.radioButton_10.setChecked(True)
        self.radioButton_10.setObjectName("radioButton_10")
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_11.setGeometry(QtCore.QRect(100, 30, 82, 17))
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_12 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_12.setGeometry(QtCore.QRect(190, 30, 82, 17))
        self.radioButton_12.setObjectName("radioButton_12")
        self.radioButton_13 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_13.setGeometry(QtCore.QRect(270, 30, 82, 17))
        self.radioButton_13.setObjectName("radioButton_13")
        self.radioButton_14 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_14.setGeometry(QtCore.QRect(350, 30, 82, 17))
        self.radioButton_14.setObjectName("radioButton_14")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(70, 340, 194, 22))
        self.dateTimeEdit.setAcceptDrops(False)
        self.dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2017, 7, 19), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit.setDate(QtCore.QDate(2017, 7, 19))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit_2.setGeometry(QtCore.QRect(70, 380, 194, 22))
        self.dateTimeEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2017, 7, 19), QtCore.QTime(12, 0, 0)))
        self.dateTimeEdit_2.setDate(QtCore.QDate(2017, 7, 19))
        self.dateTimeEdit_2.setTime(QtCore.QTime(12, 0, 0))
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(60, 90, 331, 51))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_4.setGeometry(QtCore.QRect(30, 20, 82, 17))
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_5.setGeometry(QtCore.QRect(200, 20, 82, 17))
        self.radioButton_5.setObjectName("radioButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 591, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))
        self.groupBox.setTitle(_translate("MainWindow", "ENV"))
        self.radioButton.setText(_translate("MainWindow", "UAT"))
        self.radioButton_2.setText(_translate("MainWindow", "QA"))
        self.radioButton_3.setText(_translate("MainWindow", "STG"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Teachers"))
        self.radioButton_6.setText(_translate("MainWindow", "A"))
        self.radioButton_7.setText(_translate("MainWindow", "B"))
        self.radioButton_8.setText(_translate("MainWindow", "C"))
        self.radioButton_9.setText(_translate("MainWindow", "D"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Level"))
        self.radioButton_10.setText(_translate("MainWindow", "BEG"))
        self.radioButton_11.setText(_translate("MainWindow", "ELE"))
        self.radioButton_12.setText(_translate("MainWindow", "INT"))
        self.radioButton_13.setText(_translate("MainWindow", "UPINT"))
        self.radioButton_14.setText(_translate("MainWindow", "ADV"))
        self.dateTimeEdit.setDisplayFormat(_translate("MainWindow", "yyyy/M/d h:mm AP"))
        self.dateTimeEdit_2.setDisplayFormat(_translate("MainWindow", "yyyy/M/d h:mm AP"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GL/PL"))
        self.radioButton_4.setText(_translate("MainWindow", "GL"))
        self.radioButton_5.setText(_translate("MainWindow", "PL"))

