---
env:
  uat: mobilefirst
  qa: qa
  staging: staging


api:
  login: /services/api/mobile/service/login
  studycontext: /services/api/mobile/service/studycontext
  coursestructure: /services/api/mobile/service/coursestructure
  activitycontent: /services/api/mobile/service/activitycontent

dla:
  platform: Android
  culturecode: en
  countryCode: us
  partnerCode: None
  siteVersion: development
  appVersion: 1.5.0
  productId: 1

ec:
  platform: Android
  culturecode: en
  countryCode: cn
  partnerCode: Cool
  siteVersion: development
  appVersion: 0.6.0
  productId: 4

#login:
#  serviceRequest:
#    appVersion: '%s'
#    platform: PLATFORM
#    productId: PRODUCT_ID
#    userName: USER_NAME
#    password: PASSWORD
#
#study_context:
#  serviceRequest:
#    appVersion: APP_VERSION,
#    culturecode: CULTURE_CODE,
#    platform: PLATFORM,
#    productId: PRODUCT_ID,
#    sessionId: session_id,
#    token": token
#
#course_sturcture:
#  serviceRequest:
#    level: level_id,
#    countryCode: COUNTRY_CODE,
#    partnerCode: PARTNER_CODE,
#    siteVersion: SITE_VERSION,
#    appVersion: APP_VERSION,
#    culturecode: CULTURE_CODE,
#    platform: PLATFORM,
#    productId: PRODUCT_ID,
#    sessionId: session_id,
#    token: token